### ISSUE TITLE
Queue UI Bug

### ISSUE THREAD

**Issue by CanerKaraca23** [zbrateam/Zebra#1564] opened 2020-09-21 00:06 UTC
**Describe the bug**
Queue UI bug. See video.

**To Reproduce**
Add any package to queue. Then open queue.

**Screenshots**
 https://media.discordapp.net/attachments/572784833714192395/757391962667221012/video0.mov

**Device Information:**

 - iOS Version: 12.4.8
 - Zebra Version: beta5c
 - Device Type: iPhone 5s
 - Jailbreak Type: unc0ver

**Comment by wstyres** [comment] 2020-09-21 00:12
Looks like a duplicate of #1548

**Closed by wstyres** 2020-09-21 00:12 UTC
Labels: bug
