### ISSUE TITLE
Queued tweaks not showing up in queue page

### ISSUE THREAD

**Issue by mainhathao** [zbrateam/Zebra#1555] opened 2020-09-15 10:13 UTC
**Describe the bug**
When queuing tweaks, it shows how many tweaks are queued in the small bar but when it’s expanded, there’s only 1 tweak shown and I have to dismiss the queue page and open it again to see all the queued tweaks. 

**To Reproduce**
Queue more than 2 tweaks and expand the queue page

**Expected behavior**
It’s supposed to show all queued tweaks instead of just 1
**Device Information:** 

 - iOS Version: <13.5>
 - Zebra Version: <1.2~beta5c>
 - Device Type: <iPhone Xs Max>
 - Jailbreak Type: <Odyssey>

**Comment by mainhathao** [comment] 2020-09-15 10:14
Device type: iPhone Xs Max
Jailbreak: Odyssey

**Comment by wstyres** [comment] 2020-09-15 14:23
Duplicate of #1548

**Closed by wstyres** 2020-09-15 14:23 UTC
Labels: bug
