### ISSUE TITLE
Change / page

### ISSUE THREAD

**Issue by hcm77** [zbrateam/Zebra#1891] opened 2021-07-08 19:55 UTC
**Describe the bug**
 page changes doesn’t appear,
I can’t see any news from the JB community on the change page.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by absidue** [comment] 2021-07-08 21:00
Are you only missing the reddit news or is something else missing as well on the changes tab?

**Comment by hcm77** [comment] 2021-07-08 23:59
Hi boss
I’m missing just the Reddit news.

Thanks for your kind reply

**Comment by absidue** [comment] 2021-07-09 07:40
Duplicate of #1881

**Closed** 2021-07-09 07:40 UTC
Labels: bug
