### ISSUE TITLE
Add back Swipe down in changes tab to refresh sources

### ISSUE THREAD

**Issue by Garydunlop00** [zbrateam/Zebra#1594] opened 2020-10-05 16:29 UTC
**Is your feature request related to a problem? Please describe.**
In the stable versions of zebra you were able to swipe down on both the sources and changes tab to refresh sources, Now in Zebra 1.2 beta6a you can only swipe down in the sources tab.

**Describe the solution you'd like**
Swipe down in Changes tab to refresh sources.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by absidue** [comment] 2020-10-05 16:38
Duplicate of https://github.com/zbrateam/Zebra/issues/1546

**Closed** 2020-10-05 16:38 UTC
