### ISSUE TITLE
zebra. Unable to install

### ISSUE THREAD

**Issue by chuayu** [zbrateam/Zebra#2033] opened 2023-04-12 03:37 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE> iOS 15.2.1
 - Zebra Version: <INSERT-HERE> zrbra 1.1.3.0
 - Device Type: <INSERT-HERE> iPhone 13 Pro
 - Jailbreak Type: <INSERT-HERE> Fugu15 max

**Crash Log or System Log**

**Additional context**

Hello, I come from Taiwan Province.
After jailbreaking, the plug-in installation encountered the following problems:

zebra-There is no way to install plug-ins.
I also tried to JB again, but I couldn't install any plug-ins, so I want you to help me! I really appreciate it. Have a nice day.😊

![CAF8D115-75D6-4F2F-9DCA-C78FBE9D8DB9](https://user-images.githubusercontent.com/130337871/231343313-b2543605-ce7f-4069-96ab-aceb861eefd3.png)
![A79761D2-5273-4F65-B4DB-A8B176790704](https://user-images.githubusercontent.com/130337871/231343341-d379ea1e-2a46-4ea9-acf2-4e3f029d7505.png)
![733F044B-703F-4D95-B5BC-717266E9A878](https://user-images.githubusercontent.com/130337871/231343354-d357cd85-2048-4531-895a-8e582d183bf4.png)

**Comment by iAdam1n** [comment] 2023-04-12 03:49
Duplicate of #2022

**Closed by iAdam1n** 2023-04-12 03:49 UTC
Labels: bug
