### ISSUE TITLE
zebra is not works on iphone SE 1st running ios 14.0.1😒

### ISSUE THREAD

**Issue by pisethsamoeurn** [zbrateam/Zebra#1607] opened 2020-10-27 13:49 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by absidue** [comment] 2020-10-27 14:28
Duplicate of #1604

**Closed** 2020-10-27 14:28 UTC
Labels: bug, duplicate
