### ISSUE TITLE
Empty package view after doing certain actions

### ISSUE THREAD

**Issue by eve0415** [zbrateam/Zebra#1720] opened 2021-01-10 13:42 UTC
**Describe the bug**
When doing certain actions, the tab gets empty page.

**To Reproduce**
1. Go to `Installed` tab
2. Put something in the queue
3. Open the queue
4. Slide the package and delete from the queue (Not the `Clear` button)
5. You see empty page after queue page automatically gets dismissed.
----------------------------------
1. Go to `Sources` tab
2. Go to any source and any section (But not `All Packages` section)
3. Put something in the queue
4. Open the queue
5. Slide the package and delete from the queue (Not the `Clear` button)
6. You see empty page after queue page automatically gets dismissed.
----------------------------------
1. Go to `Sources` tab
2. Go to any source and go to `All Packages` section
3. Put something in the queue
6. You see empty page when package has successfully been queued

**Expected behavior**
Reload the page properly 

**Screenshots**
If you need any videos of the explanation, comment please

**Device Information:**
 - iOS Version:  beta8a
 - Device Type: iPhone
 - Jailbreak Type: unc0ver

**Comment by wstyres** [comment] 2021-01-11 00:58
I've tried all of your steps and cannot reproduce the empty views. It is possible that this has already been fixed. Could you confirm whether or not you are queueing these packages from their depictions or from swipe actions?

**Comment by eve0415** [comment] 2021-01-11 01:06
Queuing from packages view and depictions, both happens
[Video](https://cdn.discordapp.com/attachments/764296480378322954/797994718071357450/video0.mp4)

**Comment by wstyres** [comment] 2021-01-11 01:14
I can confirm on 68c95ee78781d59cb3efff0777b58e300a277880 all of the steps you list result in a blank view but as of 00ac5ec9f06ea19c7d3534edf9ae9772c8eab707 I can no longer reproduce these bugs. I assume that they have been fixed possibly by a recently merged PR.

**Closed** 2021-02-26 12:03 UTC
Labels: bug, packages, question, scheduled
