### ISSUE TITLE
Loading the changes tab on Zebra is much slower than Cydia by a lot. - iPhone 6s | 14.0

### ISSUE THREAD

**Issue by Official-Darkn** [zbrateam/Zebra#1620] opened 2020-11-20 18:54 UTC
**Describe the bug**
Alright so Zebra and Cydia for me has the same exact repos, around 30+, but for some reason, Cydia likes to load the changes tab like 500x faster than Zebra.

Zebra - Around 5-6 seconds to load changes tab.
Cydia - Around not even 0.2 seconds to load new changes.

**To Reproduce**
Step 1 - Add up to 35 or more repos onto Zebra & Cydia
Step 2 - Go to the changes tab on both Package Managers and see the difference.

**Expected behavior**
What I expected to happen was for Zebra to load the changes tab just as fast as Cydia, as other package managers I used didn't have this problem, only Zebra.
Tested: Sileo | Installer 5 | Cydia | Zebra

**Screenshots**
Well I can't screenshot this, so I had to make a video:
MOV file of the problem: https://cdn.discordapp.com/attachments/777964996256596061/779418296616615936/video0.mov

**Device Information:** 

 - iOS Version: iOS 14.0
 - Zebra Version: 1.2~beta6a & 1.1.15-Stable
 - Device Type: iPhone 6s
 - Jailbreak Type: checkra1n 0.12.0

**Crash Log or System Log**
No crash log was provided as Zebra didn't crash, it's just the changes tab doesn't load as fast as Cydia.

**Additional context**
Nothing else to add really, I just hope this weird performance bug gets fixed.

**Comment by wstyres** [comment] 2020-11-25 16:00
I wouldn't necessarily label this as a "bug" but it is certainly not intended behavior. We're working on improving the load time of everything in Zebra 1.2 so I'm going to close the issue.

**Closed by wstyres** 2020-11-25 16:00 UTC
Labels: bug
