### ISSUE TITLE
Installed tab causes Zebra to crash.

### ISSUE THREAD

**Issue by BreckenLusk** [zbrateam/Zebra#1886] opened 2021-07-07 16:38 UTC
**Describe the bug**

Tapping on the Installed tab will crash the application on both iOS and iPadOS.

**To Reproduce**

Tap the Installed tab.

**Expected behavior**

The Installed tab will display installed packages without any issues.

**Screenshots**

**Device Information:** 

 - iOS Version: <14.5>
 - Zebra Version: <2.0 alpha 3b>
 - Device Type: <iPhone X>
 - Jailbreak Type: <odysseyra1n>

**Crash Log or System Log**

Unable at this time. Please find another source encountering this issue.

**Additional context**

N/A

**Comment by absidue** [comment] 2021-07-07 17:49
Duplicate of zbrateam/Plains#10

**Closed** 2021-07-07 17:49 UTC
Labels: bug
