### ISSUE TITLE
Crash while sources are refreshing

### ISSUE THREAD

**Issue by adhip94** [zbrateam/Zebra#1651] opened 2020-12-14 19:28 UTC
**Describe the bug**
While Zebra is refreshing sources it crashes.

**To Reproduce**
Start the app and the sources should start refreshing, crash will happen in a few seconds.

**Expected behavior**
It shouldn't crash :)

**Screenshots**

**Device Information:** 

 - iOS Version: 13.7
 - Zebra Version: 1.1.3
 - Device Type: iPhone 8 Plus
 - Jailbreak Type: checkra1n 

**Crash Log or System Log**
[Crash Log](https://www.dropbox.com/s/09psiqdprotdbxd/File%2015-12-20%2C%2012%2053%2033%20AM.txt?dl=0)
[Sources List](https://www.dropbox.com/s/01qcgd7ve8lzld9/sources.list?dl=0)

**Additional context**

**Comment by wstyres** [comment] 2020-12-14 20:24
Could you try updating to a more recent version of Zebra and seeing if the crash still occurs? The newest version is 1.1.15.

**Comment by PJ09github** [comment] 2020-12-14 22:27
> Could you try updating to a more recent version of Zebra and seeing if the crash still occurs? The newest version is 1.1.15.

Happens also on 1.2-beta6a as was reported on r/jailbreak

**Comment by wstyres** [comment] 2020-12-14 23:09
The report I saw on reddit was solved by removing a font that was installed through A-font. There was no update to Zebra that started causing these crashes, they only popped up on my dashboard yesterday so it seems something external is crashing Zebra, have not yet pinned it down.

**Comment by adhip94** [comment] 2020-12-15 05:38
> The report I saw on reddit was solved by removing a font that was installed through A-font. There was no update to Zebra that started causing these crashes, they only popped up on my dashboard yesterday so it seems something external is crashing Zebra, have not yet pinned it down.

I don't have A-font installed. I have now updated to 1.1.15, and I am unable to reproduce the crash.

**Comment by PJ09github** [comment] 2020-12-15 08:08
> The report I saw on reddit was solved by removing a font that was installed through A-font. There was no update to Zebra that started causing these crashes, they only popped up on my dashboard yesterday so it seems something external is crashing Zebra, have not yet pinned it down.

Probably caused by a repository

**Comment by adhip94** [comment] 2020-12-15 08:55
> > The report I saw on reddit was solved by removing a font that was installed through A-font. There was no update to Zebra that started causing these crashes, they only popped up on my dashboard yesterday so it seems something external is crashing Zebra, have not yet pinned it down.
> 
> 
> 
> Probably caused by a repository


A-Font is available on the below 2 repositories, should you want to check it out.

[Repo 1](https://repo.co.kr/)
[Repo 2](https://repo.rpgfarm.com/)

**Comment by wstyres** [comment] 2020-12-15 16:17
Looking at my dashboard, there have been no instances of the crash that have occurred today (the 15th of December) in any timezone. I'll leave the issue open for awhile longer to confirm that the issue is no longer happening but it is more than likely it was a faulty packages file that was downloaded and causing Zebra to crash. Not sure which repository ended up causing it but it looks like the issue has been fixed on the repository end.

**Comment by wstyres** [comment] 2020-12-17 17:34
Still no further instances of this crash. I'll close the issue.

**Closed by wstyres** 2020-12-17 17:34 UTC
Labels: bug
