### ISSUE TITLE
Contact developer button does nothing

### ISSUE THREAD

**Issue by iAdam1n** [zbrateam/Zebra#1825] opened 2021-04-28 18:27 UTC
When tapping, it'll just do nothing. iPhone SE, 14.2, unc0ver, latest Zebra version.

**Comment by iAdam1n** [comment] 2021-05-10 00:53
Stable. I don't remember the package now but I have a feeling it's broken on a few - pretty sure I checked on a package on Chariz repo so I know it's not an issue with the package control file as I work at Chariz.

**Comment by wstyres** [comment] 2021-05-10 00:58
Alright, I'll keep an eye out and see if I run into it.

**Comment by iAdam1n** [comment] 2021-05-10 00:59
Thanks.

**Comment by wstyres** [comment] 2021-05-26 16:50
Have you found any more instances of this happening? I haven't seen it myself.

**Comment by iAdam1n** [comment] 2021-05-26 16:55
It happens on multiple Chariz packages, such as Alderis. Also with Flex 3 Beta, so it seems to happen everywhere for me. Just tapping it does absolutely nothing.

**Comment by wstyres** [comment] 2021-05-26 19:44
Could you send your database file? Located at `/var/mobile/Library/Application Support/xyz.willy.zebra/zebra.db`

**Comment by iAdam1n** [comment] 2021-05-26 20:02
Sure. I've attached it. Just to confirm, I am tapping the author name on the package page when trying to do this. 
[zebra.db.zip](https://github.com/zbrateam/Zebra/files/6549355/zebra.db.zip)

**Comment by wstyres** [comment] 2021-05-26 21:45
Able to reproduce this now. Seems to be exclusive to iOS 13 and up which is why I couldn't reproduce it before. Apparently Zebra isn't allowed to send messages in-app anymore? The workaround I had in place for to just use a `mailto:` link this also was broken but I fixed it as of 9da7cc7f695891d4c2f976529488363dfc70c435 so it should at least work in the next version.

**Comment by iAdam1n** [comment] 2021-05-26 21:47
Awesome, thanks!

**Comment by wstyres** [comment] 2021-05-26 22:29
Should be fixed now in v1.1.19.

**Closed** 2021-05-27 14:10 UTC
Labels: bug, cannot reproduce, packages
