### ISSUE TITLE
[1.2] UI bugs (iOS 12)

### ISSUE THREAD

**Issue by CanerKaraca23** [zbrateam/Zebra#1331] opened 2020-05-28 16:15 UTC
**Description**
iOS 12 and below UI Issues

**Device Informations:**
 - iOS Version: iOS 12.5.1
 - Zebra Version: Zebra 1.2-beta9a
 - Device Type: iPhone 5S
 - Jailbreak Type: Chimera

**Bugs:**

- All issues from stable version: https://github.com/zbrateam/Zebra/issues/1173

- Dark mode isn't applied on new depiction UI header. [(Screenshot)](https://cdn.discordapp.com/attachments/446721039884353537/715596834936193066/image5.png)
- There are some white spaces on new depiction UI. [(Screenshot)](https://cdn.discordapp.com/attachments/446721039884353537/715596834604580954/image4.png)
- Dark/Light mode transition and text color issues. [(Screenshot)](https://cdn.discordapp.com/attachments/446721039884353537/715596834265104414/image3.png) [(Screenshot)](https://cdn.discordapp.com/attachments/570634688813858820/822113198148550666/image3.png) [(Screenshot)](https://cdn.discordapp.com/attachments/570634688813858820/822113198395490344/image4.png) [(Screenshot)](https://cdn.discordapp.com/attachments/570634688813858820/822113198630502440/image5.png) [(Screenshot)](https://cdn.discordapp.com/attachments/570634688813858820/822113198822916206/image6.png) [(Screenshot)](https://cdn.discordapp.com/attachments/570634688813858820/822113199025160192/image7.png) [(Screenshot)](https://cdn.discordapp.com/attachments/570634688813858820/822121416597176330/image0.png)
- Incorrect colors on top and bottom on menus. [(Screenshot)](https://user-images.githubusercontent.com/37447503/93830260-63459100-fc78-11ea-9b20-2e67ddc6910f.png)
- Wrong text color on new filter screen. [(Screenshot)](https://user-images.githubusercontent.com/37447503/102727074-85f94b80-4334-11eb-9670-1557b3a87562.png)
- Incorrect status bar colors on some tabs and repo adding screen. [(Screenshot)](https://user-images.githubusercontent.com/37447503/102726945-9a891400-4333-11eb-8bb5-ac349dca2eec.png)  [(Screenshot)](https://cdn.discordapp.com/attachments/570634688813858820/822113197544439808/image0.png) [(Screenshot)](https://user-images.githubusercontent.com/37447503/102726949-9e1c9b00-4333-11eb-9be2-dbc5279ddd1c.png) [(Screenshot)](https://cdn.discordapp.com/attachments/570634688813858820/822113197728727101/image1.png) [(Screenshot)](https://user-images.githubusercontent.com/37447503/90330502-c2e3b900-dfb5-11ea-84c3-d6b1c8f7965d.png)

**Comment by gkeep** [comment] 2020-05-28 18:25
> Repo adding screen located wrong and we can't click cancel button (Screenshot)

Sometimes it happens, sometimes it doesn't. 
Looks like the cause is changing Light/Dark mode on home page. [Video](https://i.imgur.com/jC1AqZJ.mp4)



Can confirm the rest.

**Comment by gkeep** [comment] 2020-05-29 09:57
> Looks like the cause is changing Light/Dark mode on home page. [Video](https://i.imgur.com/jC1AqZJ.mp4)

Actually, it happens on stable (1.1.9) too.

**Comment by CanerKaraca23** [comment] 2020-05-29 10:08
> > Looks like the cause is changing Light/Dark mode on home page. [Video](https://i.imgur.com/jC1AqZJ.mp4)
> 
> Actually, it happens on stable (1.1.9) too.

I will add this issue in this topic https://github.com/wstyres/Zebra/issues/1173

**Comment by CanerKaraca23** [comment] 2020-05-29 10:21
Updated.

**Comment by gkeep** [comment] 2020-05-29 10:24
Btw, you can install [Peekable](https://repo.packix.com/package/com.ryannair05.peekable) to simulate 3d touch :)

**Comment by CanerKaraca23** [comment] 2020-05-29 10:29
> Btw, you can install [Peekable](https://repo.packix.com/package/com.ryannair05.peekable) to simulate 3d touch :)

I always wanted to have a 3D touch device, this tweak was good I learned, thanks!

**Comment by PoomSmart** [comment] 2020-05-30 03:36
Black status bar bug fixed as of 4425116ada6d25eaaea4466203c706a65319ed82

**Comment by CanerKaraca23** [comment] 2020-06-03 22:28
![E8A3B42F-2921-4798-AB25-1F80548B3E26](https://user-images.githubusercontent.com/37447503/83695382-9816d500-a602-11ea-91cd-4dc9224c3e2d.png)
More transition issues...

**Comment by gkeep** [comment] 2020-06-04 06:12
If you’re talking about the community news headers, we can’t translate them, since they are pulled directly from Reddit.

**Comment by CanerKaraca23** [comment] 2020-06-04 07:03
> If you’re talking about the community news headers, we can’t translate them, since they are pulled directly from Reddit.

No it's dark/light transition issue. Not translation : )

**Comment by gkeep** [comment] 2020-06-04 07:05
Oh, blind me. Thought it said translation not transition 🤦

**Comment by CanerKaraca23** [comment] 2020-08-16 08:45
New issue added. Dark statusbar on new repo adding screen.

**Comment by CanerKaraca23** [comment] 2020-09-21 23:08
On new beta (6a) This dark mode issue showed.

![6A39B12F-2AFE-491E-B9AE-644D3EA7D999](https://user-images.githubusercontent.com/37447503/93830260-63459100-fc78-11ea-9b20-2e67ddc6910f.png)

**Comment by CanerKaraca23** [comment] 2020-09-27 20:21
It's really ugly, can you fix it @wstyres ? It's occured on 6a beta.

**Comment by CanerKaraca23** [comment] 2020-12-20 23:31
Updated.

**Comment by CanerKaraca23** [comment] 2021-03-18 14:40
Updated.

**Comment by wstyres** [comment] 2021-05-26 01:16
In the 2.0 alpha I've removed the iOS 12 dark mode for the time being. I'm going to close the issue now but this does not mean that the feature will not return it is more so for housekeeping reasons as if the feature does return it will have its own problems.

**Closed by wstyres** 2021-05-26 01:16 UTC
Labels: beta, bug
