### ISSUE TITLE
Zebra Refreshes Sources Automatically

### ISSUE THREAD

**Issue by CanerKaraca23** [zbrateam/Zebra#1677] opened 2020-12-25 06:22 UTC
**Describe the bug**
 Zebra automatically refreshes sources on startup even I disabled automatic refresh in settings after beta7b.

**To Reproduce**
 Start Zebra

**Expected behavior**
 Fix

**Screenshots**
 -

**Device Information:** 

 - iOS Version: <12.4.8>
 - Zebra Version: <1.2 beta7c>
 - Device Type: <iPhone 5s>
 - Jailbreak Type: <unc0ver>

**Crash Log or System Log**
 -

**Additional context**
 -

**Comment by absidue** [comment] 2020-12-25 09:08
I'm guessing you are referring to the loading wheel on the sources tab after opening the app?

This is intended behaviour and is not refreshing the sources (check network activity if you don't believe me). During that time Zebra is comparing the database installed list with apt's install list and importing missing packages as well as some other background tasks. As mentioned above this does not include refreshing remote sources.

I'm going to close this as it isn't a bug. If you have suggestions for a better ways to show that those background tasks are running, please open a discussion for it.

**Closed by absidue** 2020-12-25 09:08 UTC
Labels: bug
