### ISSUE TITLE
Does not authorize user to buy paid packages when putting in queue

### ISSUE THREAD

**Issue by eve0415** [zbrateam/Zebra#1697] opened 2020-12-31 13:24 UTC
**Describe the bug**
Try to install a paid package that you have not paid yet. It will not pop up like before but put straightly in queue mark as install.
`Get` button does not show cost for most packages.

**To Reproduce**
Try to install a paid package that you have not paid yet. You can press `Get` button or slide and press install.

**Expected behavior**
Pop up to authorize and pay.

**Device Information:**
 - iOS Version: 13.5
 - Zebra Version: beta7d
 - Device Type: iPhone
 - Jailbreak Type: unc0ver

**Comment by wstyres** [comment] 2021-01-11 00:54
I'm not able to reproduce this. It is possible that it has already been fixed. Could you verify a source and package that this issue occurs with? I'm trying it with BetterAlarm on Chariz and it presents the payment screen like expected.

**Comment by eve0415** [comment] 2021-01-11 00:57
Looks like this issue is only for Packix

**Comment by wstyres** [comment] 2021-01-11 01:06
Ok, looks like the issue was some whitespace that was left over when parsing the tags. Should be fixed in 00ac5ec9f06ea19c7d3534edf9ae9772c8eab707.

**Closed** 2021-02-26 12:02 UTC
Labels: beta, bug, queue, scheduled
