### ISSUE TITLE
Packages section empty and Changes section not updating in v 1.2~beta5a/b/C 

### ISSUE THREAD

**Issue by PJ09github** [zbrateam/Zebra#1554] opened 2020-09-15 09:47 UTC
**Describe the bug**
Packages section empty and Changes section is not updating after a full refresh

**To Reproduce**
Use v 1.2~beta5a/b/C and refresh

**Device Information:** 

 - iOS Version: iOS 13.5/13.6/13.6.1/13.7
 - Zebra Version: 1.2~beta5a/b/c
 - Device Type: iPhone 6S, / 7 Plus, X, iPad Pro
 - Jailbreak Type: checkra1n

**Comment by eve0415** [comment] 2020-09-15 10:40
Duplicate of #1543

**Closed** 2020-09-15 14:23 UTC
Labels: bug
