### ISSUE TITLE
Zebra crashes as soon as I try to queue a tweak, search for a tweak or sign in to an account

### ISSUE THREAD

**Issue by RickyHunter024** [zbrateam/Zebra#2013] opened 2022-12-13 23:30 UTC
**Describe the bug**
 Basically what the title says

**To Reproduce**

Case 1
1-Choose a tweak to install
2-Queue it.
Case 2
1-Try to sign in with any repo account
Case 3
1-Try to use the search tab

**Expected behavior**

Case 1
Add to queue
Case 2 
Open in-app browser to sign in
Case 3 
Open the search tab
 
**Screenshots**

**Device Information:** 
 - iOS Version: <15.1>
 - Zebra Version: <1.1.29>
 - Device Type: <iPhone 6s>
 - Jailbreak Type: <palera1n>

**Crash Log or System Log**

Date: 14/12/2022, 1:17 AM
Process: Zebra
Bundle id: xyz.willy.Zebra
Device: iPhone 6s, iOS 15.1
Bundle version: 1.1.29

Exception type: NSInternalInconsistencyException
Reason: UIViewController is missing its initial trait collection populated during initialization. This is a serious bug, likely caused by accessing properties or methods on the view controller before calling a UIViewController initializer. View controller: <ZBQueueViewController: 0x1011e2e50>
Culprit: Unknown

**Additional context**

Also happens in version 1.1.30 

Edit: Updated to include what was found latest

**Comment by y0y0kh** [comment] 2022-12-16 14:06
crash on ios 14.3

**Comment by Oliverkiller** [comment] 2022-12-19 23:22
Just tried it, same thing happening

**Comment by iAdam1n** [comment] 2022-12-19 23:24
That is weird. Doesn't happen here on 15.7.2 with palera1n. Do you have any tweaks installed that might interfere with Zebra?

**Comment by Oliverkiller** [comment] 2022-12-19 23:24
I just restored rootfs so nope

**Comment by iAdam1n** [comment] 2022-12-19 23:25
It shouldn't make any difference but what tweak did you try to queue?

**Comment by Oliverkiller** [comment] 2022-12-19 23:26
I tried to queue dodo by ginsu & even tried reinstalling zebra itself

**Comment by iAdam1n** [comment] 2022-12-19 23:32
Would you mind emailing us a crash log to team@getzbra.com?

**Comment by Oliverkiller** [comment] 2022-12-19 23:34
Sure

**Comment by Oliverkiller** [comment] 2022-12-19 23:41
done

**Comment by Oliverkiller** [comment] 2022-12-20 00:06
I was playing around with zebra just now trying to sign in or view my account and it seems this also crashes zebra

**Comment by iAdam1n** [comment] 2022-12-20 00:09
It appears to be the cause as another crash someone else reported after looking at the log. We'll investigate and fix it asap. Thank you for reporting it.

**Comment by Oliverkiller** [comment] 2022-12-20 00:10
Np, just hoping it gets fixed soon. Something else, should removing the database help in any way?

**Comment by iAdam1n** [comment] 2022-12-20 00:32
It seems it's an issue from our end so I doubt it.

**Comment by Oliverkiller** [comment] 2022-12-26 23:26
Any updates on this issue?

**Comment by iAdam1n** [comment] 2022-12-26 23:26
Not yet but we're working on it.

**Comment by AD4MWR** [comment] 2022-12-28 18:17
Hey, I also have this issue. I’m on iOS 15.1 too but on an iPhone X. Jailbroken with Palera1n. Running the latest version of Zebra (1.1.30). I get the same crash log as OP. App also crashes when I try and search for a package. Not sure if OP also has this issue? Hoping the crashes can be fixed soon though as really missing zebra. Thanks

**Comment by Oliverkiller** [comment] 2022-12-28 20:56
Since I got a reply from the team then it should be in the works right now and to be honest I understand why bugs rn will take a long time to be fixed as bugs are all over the place either from the newly released Xina or palera1n which is filled to the brim with bugs I really hope this bug gets fixed soon because Sileo isn’t the best sometimes especially on palera1n and yes it seems trying to access the search tab crashes zebra with the same log

**Comment by Oliverkiller** [comment] 2023-01-11 18:10
Is there an update on this or nothing yet? I am willing to test any beta as well.

**Comment by iAdam1n** [comment] 2023-01-11 18:14
Not yet, we're looking at it.

**Comment by fiatuno49** [comment] 2023-01-16 11:06
Zebra dearch 1.1.30 crash on I8 iOs 15.0.2 Palera1n IB
Any progress yet
Thanks
Tony

**Comment by iAdam1n** [comment] 2023-01-16 11:18
Not yet.

**Comment by RickyHunter024** [comment] 2023-01-16 12:22
> Zebra search 1.1.30 crash on I8 iOs 15.0.2 Palera1n JB
> 
> Any progress yet
> 
> Thanks
> 
> Tony

Ik I am not the dev but just to make sure it's the same bug mind sending your crash log??

**Comment by iAdam1n** [comment] 2023-01-16 15:21
It is, they emailed us it.

**Comment by RickyHunter024** [comment] 2023-02-11 14:27
Any updates on this?

**Comment by iAdam1n** [comment] 2023-02-11 14:57
Not yet. I tried to get it to happen on iOS 15.7.3 on my 6s Plus but it wouldn’t crash. I could reproduce it in the past though. We’ll let you know when fixed.

**Comment by iAdam1n** [comment] 2023-05-03 05:39
Fixed with 1.1.31.

**Closed by iAdam1n** 2023-05-03 05:39 UTC
Labels: bug
