### ISSUE TITLE
Sources not refreshing

### ISSUE THREAD

**Issue by seanie86** [zbrateam/Zebra#1558] opened 2020-09-16 15:27 UTC
**Describe the bug**
with the newest beta 1.2 5c I have had a lot of trouble with the sources not refreshing and not being able to see any new releases.

**To Reproduce**
install the beta and try to refresh sources.

**Expected behavior**

I would expect the sources to refresh and then to see any new releases.
**Screenshots**

**Device Information:** im on an 8 plus running 13.4.1

 - iOS Version:13.4.1<INSERT-HERE>
 - Zebra Version: <INSERT-HERE>1.2 beta 5c
 - Device Type: <iphone>
 - Jailbreak Type: <uncover>

**Crash Log or System Log**
i don't have a crash log with the newest beta but I can share old crashes if needed.

**Additional context**

**Comment by wstyres** [comment] 2020-09-16 15:28
How do you know that there are not any new releases? Could you explain a little bit more about the problem you're experiencing? Specifically how you know that nothing is being updated.

**Comment by seanie86** [comment] 2020-09-17 15:37
Usually, I will see on Twitter or on the jailbreak subreddit there are new tweaks that came out but when I refresh my sources it will take a very long time, and then it might say 5 sources could not be refreshed but it doesn't tell me which ones. Also at the top of the releases, it has the time and date for when it was last refreshed and it seems to be stuck on a date from the day before. But today it had refreshed it from the last time I refreshed my sources. But it didn't do it right away for some reason. Also, a few of the stores are having trouble letting me sign in. I think NiceiOS and another one. Thanks for the response too.

**Comment by wstyres** [comment] 2020-09-20 20:53
This could be caused by a number of reasons but I've added a fix for another issue I found so hopefully it is resolved as of eb4b7a7a30f5ddb676aa553213ee53de321caded. Let me know when the next beta comes out.

**Comment by eve0415** [comment] 2020-09-21 22:24
Can confirm it has been fixed in beta 6a

**Closed** 2020-09-22 13:42 UTC
Labels: bug, scheduled, sources
