### ISSUE TITLE
Duplicate search results

### ISSUE THREAD

**Issue by eve0415** [zbrateam/Zebra#1665] opened 2020-12-20 23:38 UTC
**Describe the bug**
Search for some packages. Some get duplicate search result.

**To Reproduce**
1 Search for some packages in the search tab
2 We also get duplicate packages in "Author" (More packages from author)

**Expected behavior**
Show only one package for same bundle identifier

**Screenshots**
![image](https://user-images.githubusercontent.com/40632436/102727242-e5248380-4367-11eb-90f4-b626e14377dd.png)
![image](https://user-images.githubusercontent.com/40632436/102727259-fbcada80-4367-11eb-8484-b43b54f29d1c.png)

**Device Information:**
 - iOS Version: 13.5
 - Zebra Version: beta7b
 - Device Type: iPhone
 - Jailbreak Type: unc0ver

**Comment by eve0415** [comment] 2020-12-25 03:37
Update: We also get duplicate packages in "Author" (More packages from author)

**Comment by PoomSmart** [comment] 2020-12-29 05:05
Do we still see this in beta 7c? @eve0415

**Comment by eve0415** [comment] 2020-12-29 05:11
Yes

**Comment by eve0415** [comment] 2020-12-31 06:56
The same goes for filtering author in the settings

**Comment by PoomSmart** [comment] 2021-01-01 03:49
@eve0415 Can we examine your `zebra.db` ?

**Comment by eve0415** [comment] 2021-01-01 05:13
https://www.icloud.com/iclouddrive/0nVjaVS5GY_nwyZwOD5fJPk2g#zebra-2
@PoomSmart

**Comment by PoomSmart** [comment] 2021-01-01 06:10
Bizarre. Cannot reproduce on my own..

**Comment by eve0415** [comment] 2021-01-01 06:13
I think the duplicate one is getting from dpkg status because installed package are always being duplicated. Some packages even doesn't fetch a proper description from Internet. How do you think?

**Comment by PoomSmart** [comment] 2021-02-10 02:46
Fixed in PR #1744

**Closed** 2021-02-26 12:03 UTC
Labels: beta, bug, low, scheduled, search
