### ISSUE TITLE
Zebra not loading sources properly after updating from 1.1.13 to 1.2-beta5(a/b/c)

### ISSUE THREAD

**Issue by whiteblacksmiths** [zbrateam/Zebra#1561] opened 2020-09-20 00:23 UTC
**Describe the bug**

- when i rejailbroke my phone after restoring it, i installed the latest non-beta version so that i can copy&paste my sources backup list. everything works fine, but after i am done with setting up the sources, i upgrade to the latest zebra beta and the entire app always glitches out.
- my installed list will be empty except for an update to a specific package (ceadd repo’s [https://cydia.ceadd.ca] Cydia Icon package if it matters) but that package does not even have a newer version than the one i installed. 
- refreshing sources seems to work as intended with no error, but many of the sources do not have any package inside. 
- i tried resetting sources cache, deleting all sources (after deleting i re-downgraded zebra so i could copy&paste my sources list again), then the issue would resurface. 
- when *within the zebra beta* i try to downgrade zebra to the non-beta version, an dependency error would pop up saying i do not have dpkg installed thus zebra cannot perform the downgrade
- when trying to install other tweaks, another dependency error would pop up saying i need mobilesubstrate, although i am jailbroken with u0 and substitute is installed. 
- i also found an animation bug/glitch; after tapping on a source and swiping left quickly to go back to the sources list, the animation “overshots” and shows a black screen partially
- i tried downgrading to 1.2-beta4c and my installed tweaks tab works perfectly, but all my sources have no package in them. 
 
**To Reproduce**

- upgrade and downgrade between latest zebra betas and non-betas, for me, i tried switching between zebra 1.1.13 and  1.2-beta5c, beta5b, beta5a, all of which caused similar issues. 
- to reproduce the animation bug, i think from the sources tab, you have to quickly press into a source (to view the contents), then swipe left to go back to main sources page. i did that several times (about 6/7) and afterwards the bug shows. 
**Screenshots**

i uploaded some screenshots of the installed tweaks tab, the dependency error popups, and a screen recording of the animation glitch
https://imgur.com/a/AmsEv4w

**Device Information:** 

 - iOS Version: <13.5>
 - Zebra Version: <1.2-beta5a, 1.2-beta5b, 1.2-beta5c; 1.2-beta4c; 1.1.13>
 - Device Type: <iPX>
 - Jailbreak Type: <u0>

**Comment by gkeep** [comment] 2020-09-20 20:16
Duplicate of #1543. Fixed in 3d4ac2cfa5ff8c3ff7bf8a97e3fbbd0bc1c1e14e.

**Closed** 2020-09-20 20:25 UTC
Labels: bug
