### ISSUE TITLE
After importing a .deb the queue safe area constraint is off

### ISSUE THREAD

**Issue by crivera2712** [zbrateam/Zebra#1448] opened 2020-06-30 16:20 UTC
**Describe the bug**
The queue buttons “Clear” and “Install” are way too much to the top, close to the Safe Area. 

Also I have to tap twice the Get button to the queue to show up, and doesn’t dismiss the get interface automatically.

**To Reproduce**
Do “Open on Zebra” on any .deb file you may have around.

**Expected behavior**

I expected the “Get” button to work on the first attempt and dismiss the queue view, jumping to the queue. I also expect the queue to be aware of the safe area at the top.

**Screenshots**

![image](https://user-images.githubusercontent.com/65054699/86150547-2a57af00-bac3-11ea-9cef-82437f1f22f5.png)

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Zebra 1.2 beta1b
 - Device Type [e.g. iPhone or iPad]: iPhone XS
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver 

**Additional context**

**Comment by wstyres** [comment] 2020-09-12 19:51
Does this problem still occur? It looks like it may be a bug that is caused by a tweak

**Comment by eve0415** [comment] 2020-09-13 00:35
https://discord.com/channels/566255609251364864/572784833714192395/754499976234795088
I don’t have any tweak that changes Zebra.
Still, if you tried to install a deb package, and press get button second time (the view doesn’t dismiss automatically) the queue page is at the top then expected.

**Comment by wstyres** [comment] 2020-09-18 22:54
Should be fixed as of 5b92d290f9d22756ea52026d42d3a0852041c0f3.

**Closed** 2020-09-21 17:08 UTC
Labels: bug, low, queue, scheduled
