### ISSUE TITLE
It doesn’t show packages in changes tab in the latest update

### ISSUE THREAD

**Issue by Pieloma** [zbrateam/Zebra#1682] opened 2020-12-27 03:44 UTC
I have iPhone 6s,iOS 14 jailbroken with oddesyra1n (checkra1n). In the latest update nothing shows up in changes tab I tried everything but doesn't help ![image](https://user-images.githubusercontent.com/74014254/103163435-d86eb800-47cb-11eb-9fa6-95dfb4641775.png)

**Comment by wstyres** [comment] 2020-12-29 18:16
Are you able to use other features of the app?

**Comment by Pieloma** [comment] 2020-12-30 17:33
> Are you able to use other features of the app?

Nope

**Comment by Pieloma** [comment] 2020-12-31 00:40
After today's update I still don't see packages in changes but now I see packages in installed. :)

**Comment by wstyres** [comment] 2020-12-31 03:41
I've just released version 1.2~beta7d. Please update to that version and give it a try. If the issue is still occurring. Please delete your database located at `/var/mobile/Library/Application Support/xyz.willy.zebra/zebra.db` and try opening Zebra again.

**Comment by eve0415** [comment] 2020-12-31 13:31
This happens not only in the changes tab but also in source tab.
This mostly occurs when trying to use Zebra from the background (Not closing Zebra, but press home button and after a while, open Zebra from background)
This was tested on beta7d
I think Zebra is not reading the database after returning from background

**Comment by Pieloma** [comment] 2021-01-01 02:37
> I've just released version 1.2~beta7d. Please update to that version and give it a try. If the issue is still occurring. Please delete your database located at `/var/mobile/Library/Application Support/xyz.willy.zebra/zebra.db` and try opening Zebra again.

I tried but no luck

**Comment by PoomSmart** [comment] 2021-01-10 02:59
@Pieloma You could try "Reset Sources Cache" in beta 8a.

**Comment by wstyres** [comment] 2021-02-02 18:54
Closed due to inactivity.

**Closed by wstyres** 2021-02-02 18:54 UTC
Labels: bug, question
