### ISSUE TITLE
Zebra doesn't install tweaks always

### ISSUE THREAD

**Issue by RickyHunter024** [zbrateam/Zebra#2029] opened 2023-03-24 15:13 UTC
**Describe the bug**
--> 
When I queue a tweak it just downloads the tweak but doesn't install it same happens if you queue multiple tweaks

**To Reproduce**
-->
1. Download & install a singular tweak and press close (Done if available) 
2. queue another tweak right after it and try to download & install

OR

Try to queue multiple tweaks after respring 
**Note:** it should be at least more than 10 packages it happen. Take snowboard and it's extensions for example 

**Expected behavior**
-->
Download and install normally

**Screenshots**
-->
[image](https://user-images.githubusercontent.com/38816578/227563085-e51b1c29-6ee3-48e9-9820-b575d49db5be.png)

**Device Information:**
-->
 - iOS Version: <iOS 15.7.3>
 - Zebra Version: <1.1.30>
 - Device Type: <iPhone 6s>
 - Jailbreak Type: <Palera1n-c beta 5>

**Crash Log or System Log**
-->
This is the crash log from KrashKop

Incident Identifier: 1DD691BE-12B4-45B9-AB81-2D7BCAEE6954
CrashReporter Key:   336c723a4e284dbdf9cd4d159228600f4ee4fee3
Hardware Model:      iPhone8,1
Process:             apt [11284]
Path:                /usr/bin/apt
Identifier:          apt
Version:             ???
Code Type:           ARM-64 (Native)
Role:                Unspecified
Parent Process:      Zebra [11178]
Coalition:           xyz.willy.Zebra [862]

Date/Time:           2023-03-24 16:57:20.3784 +0200
Launch Time:         2023-03-24 16:57:19.8538 +0200
OS Version:          iPhone OS 15.7.3 (19H307)
Release Type:        User
Baseband Version:    9.61.00
Report Version:      104

Exception Type:  EXC_GUARD (SIGKILL)
Exception Subtype: GUARD_TYPE_VIRT_MEMORY
Exception Message: offset=0x000000012dc84000, flavor=0x00000001 (DEALLOC_GAP)
Exception Codes: 0x0000000000000000, 0x000000012dc84000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: GUARD 11529215050363437056 

Triggered by Thread:  0

Thread 0 name:   Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	       0x1bc3de9e0 _kernelrpc_mach_vm_deallocate_trap + 8
1   libsystem_kernel.dylib        	       0x1bc3dfaac mach_vm_deallocate + 84
2   libsystem_malloc.dylib        	       0x192d33dc4 mvm_deallocate_pages + 140
3   liblzma.5.dylib               	       0x104816bd0 0x104800000 + 93136
4   liblzma.5.dylib               	       0x104808014 0x104800000 + 32788
5   liblzma.5.dylib               	       0x10480c30c 0x104800000 + 49932
6   liblzma.5.dylib               	       0x104808014 0x104800000 + 32788
7   liblzma.5.dylib               	       0x10480d994 0x104800000 + 55700
8   liblzma.5.dylib               	       0x104808014 0x104800000 + 32788
9   liblzma.5.dylib               	       0x10480839c lzma_end + 36
10  libapt-pkg.6.0.0.dylib        	       0x104ce0400 0x104c44000 + 640000
11  libapt-pkg.6.0.0.dylib        	       0x104ce01e4 0x104c44000 + 639460
12  libapt-pkg.6.0.0.dylib        	       0x104cda944 FileFd::Close() + 284
13  libapt-pkg.6.0.0.dylib        	       0x104cdb728 FileFd::~FileFd() + 32
14  libapt-pkg.6.0.0.dylib        	       0x104d4c13c 0x104c44000 + 1081660
15  libapt-pkg.6.0.0.dylib        	       0x104d70ea8 pkgPackageManager::OrderInstall() + 372
16  libapt-pkg.6.0.0.dylib        	       0x104d717c8 pkgPackageManager::DoInstall(APT::Progress::PackageManager*) + 32
17  libapt-private.0.0.0.dylib    	       0x104a3701c InstallPackages(CacheFile&, APT::PackageContainer<std::__1::vector<pkgCache::PkgIterator, std::__1::allocator<pkgCache::PkgIterator> > >&, bool, bool, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, CommandLine const&) + 4928
18  libapt-private.0.0.0.dylib    	       0x104a3e348 DoInstall(CommandLine&) + 5520
19  libapt-pkg.6.0.0.dylib        	       0x104cc7138 CommandLine::DispatchArg(CommandLine::Dispatch const*, bool) + 216
20  libapt-private.0.0.0.dylib    	       0x104a2f674 DispatchCommandLine(CommandLine&, std::__1::vector<CommandLine::Dispatch, std::__1::allocator<CommandLine::Dispatch> > const&) + 48
21  apt                           	       0x1047732fc main + 240
22  dyld                          	       0x10488c4d0 start + 444

Thread 1:
0   libsystem_pthread.dylib       	       0x1dcf40934 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x000000012d000000   x2: 0x0000000001800000   x3: 0x0000000000000100
    x4: 0xffffffffffffedf8   x5: 0x0000000000000008   x6: 0x000000000000005a   x7: 0x0000000000001000
    x8: 0x0000000000000000   x9: 0x000000000000019c  x10: 0x000000000000019e  x11: 0x0000000000000018
   x12: 0x000000012bf08000  x13: 0x00000001f670d450  x14: 0x0000000000000000  x15: 0x000000012bf0a6d0
   x16: 0xfffffffffffffff4  x17: 0x000000000000019c  x18: 0x0000000000000000  x19: 0x0000000001800000
   x20: 0x000000012d000000  x21: 0x0000000000000203  x22: 0x0000000000000970  x23: 0x0000000000001000
   x24: 0x0000000104dcc4f0  x25: 0x0000000000000000  x26: 0x0000000000000001  x27: 0x0000000104dcc508
   x28: 0x0000000104a68b58   fp: 0x000000016b692d60   lr: 0x00000001bc3dfaac
    sp: 0x000000016b692d40   pc: 0x00000001bc3de9e0 cpsr: 0x60000000
   far: 0x000000012c020008  esr: 0x56000080  Address size fault

Binary Images:
       0x1bc3de000 -        0x1bc411fff libsystem_kernel.dylib arm64  <af565ccf2e9d37b0ae60c41279a0025a> /usr/lib/system/libsystem_kernel.dylib
       0x192d2e000 -        0x192d4efff libsystem_malloc.dylib arm64  <3dfd377ea7063e45be5243e27cef7214> /usr/lib/system/libsystem_malloc.dylib
       0x104800000 -        0x104827fff liblzma.5.dylib arm64  <39ae7faf4add3a85a4f33e552cbd5a62> /usr/local/lib/liblzma.5.dylib
       0x104c44000 -        0x104dc3fff libapt-pkg.6.0.0.dylib arm64  <03496b21b1cd3c1499237ddf9a2e7b6d> /usr/lib/libapt-pkg.6.0.0.dylib
       0x104a18000 -        0x104a6bfff libapt-private.0.0.0.dylib arm64  <b303b057389432f8ae8dfb0a0fb38916> /usr/lib/libapt-private.0.0.0.dylib
       0x10476c000 -        0x104773fff apt arm64  <d392c0ba70ca3e42baecacd981a43537> /usr/bin/apt
       0x104874000 -        0x1048c7fff dyld arm64  <58ab16ced7e032d3946d4f68fb1a4a17> /cores/dyld
       0x1dcf3f000 -        0x1dcf4ffff libsystem_pthread.dylib arm64  <ad10e93329043dbc9575707033bf6949> /usr/lib/system/libsystem_pthread.dylib

EOF

**Additional context**

**Comment by iAdam1n** [comment] 2023-03-24 15:32
Duplicate of https://github.com/zbrateam/Zebra/issues/2022.

**Closed by iAdam1n** 2023-03-24 15:32 UTC
Labels: bug
