### ISSUE TITLE
1.2 Design Discussion - Community Depictions

### ISSUE THREAD

**Issue by wstyres** [zbrateam/Zebra#1309] opened 2020-05-27 22:48 UTC
Zebra 1.2 is going to contain a complete UI redesign of the application and many things are going to be changed. We want to be sure all of the bases are covered so this issue will serve as a discussion forum for the new **Package Depiction** views and the features that come along with it. We'd like constructive criticism from Users, Developers, and Repo Maintainers alike so that we can make these new depictions easy to use and as informational as possible.

The first 1.2 beta introduced a redesigned depiction view for all packages as well as a new "native depiction" feature that all packages can adopt. We'd like these new depictions to be available to everyone and that is why simplicity was a key part in the making of this format.

We took a different approach to native depictions that preserves web depictions (and advertisements), while still being able to improve upon package depictions without them. We didn't want to (fully) implement Sileo's Depiction format as we found that it is very catered towards Sileo's use and not very open to other package managers. While the Sileo format can also be very customizable, we found that the JSON format can quickly get confusing and very messy. Zebra's approach uses simple tags that you can add to your control file.

We are planning on adding support for automatically converting Sileo's depictions in the next beta but for the time being we'd appreciate input on the new format as our goal is to make having native depictions extremley simple without the need for much server interaction. 

A detailed description of all the new Native Depiction features is available [on the Zebra Wiki](https://github.com/wstyres/Zebra/wiki/Community-Depictions).

### Native Depictions

1             |  2 
:-------------------------:|:-------------------------:
![](https://i.imgur.com/PCvAREz.png)  |  ![](https://i.imgur.com/WDoUSZA.png)

### Web Depictions

1             |  2
:-------------------------:|:-------------------------:
![](https://i.imgur.com/A0tOpny.png)  |  ![](https://i.imgur.com/77NIkkP.png)
#### Known Issues
- Dark mode doesn’t work on iOS 12 and below for the depiction screen
- Sometimes, when in landscape mode, the margins in the depiction screen are wrong
- The shadow under the image header of a depiction may disappear
- Tapping a link in a package desceription or changelog does not currently work

#### Things we're still planning on adding:
- Converting `SileoDepiction` tags into the Zebra format where applicable
- Slight redesign to the "Installed Files" view
- New "Support" view for contacting authors and maintainers (as the popup is temporary)
- Listing Dependencies and Conflicts before queueing the package for install
- Listing Compatibility (using existing compatible::) formats
- Support for the `Support` tag used in Cydia
- Show screenshots in full screen if they're tapped on
- Suggestions?

#### Things we're still thinking about:
- Redesigning the "More By Author" view
- Using the already existing debian changelog format instead of a multiline `Changelog` tag

We’re still looking for feedback on this new depiction view, as well as where we can still improve and add upon them. Please let us know your thoughts.

**Comment by eve0415** [comment] 2020-05-27 23:28
![C2A6E1B8-00D1-4E98-A03E-92A5DF2A9605](https://user-images.githubusercontent.com/40632436/83081968-f4d33680-a0bc-11ea-9d9d-30494e2b8524.png)

Suggestion to change font size of version number (name) and the description. Bigger for the number I guess. It’s a little bit too small. Also, the link that’s in blue are hard to read.

**Comment by 23Aaron** [comment] 2020-05-27 23:58
My input as someone who works at a major repo (my views do not reflect that of Dynastic as a whole):

Adding another depiction standard at this point is already frustrating enough for major repos to support (even if the argument is that this change isn't made with large repos to support, smaller repos will look to us as an example/guidance), and for smaller repos it will end up causing fragmentation, as devs will likely not be able to focus on ensuring all depictions look good, so some will optimise for Sileo and others for Zebra. Fragmentation at this point along the development of Sileo's native depictions (a phrase I really hope Zebra doesn't adopt, as it'll only cause confusion for users, devs and maintainers) is something we should really be aiming to avoid. 

If the aim is simplicity, why would a developer not simply stick with existing webview depictions?

I take issue with the assessment that 

> We didn't want to (fully) implement Sileo's Depiction format as we found that it is very catered towards Sileo's use and not very open to other package managers

As Zebra seems to be the only package manager which is taking this stance. Installer 5 managed to integrate Sileo's native depictions with no issues, along with Parcility, and to my knowledge, Saily. 

I also believe that the reasoning that

> the JSON format can quickly get confusing and very messy

is a strange one, because you're eschewing a known entity, and one well documented for an approach that requires additions to control files that seem like a completely new addition to something else entirely? 

All in all, my thoughts on this is that it's a confusing move, I don't see who it seeks to benefit, and only seems to cause migration in an area that was currently doing fine without it. I really enjoy Zebra as a whole, and I'm sure this move has good intentions behind it, but I can't see it benefitting the community as a whole.

**Comment by Diatrus** [comment] 2020-05-28 00:05
I’d like to note that the native depictions introduced by Sileo are well documented and open to change, as stated from the beginning. They were made to introduce a new standard, and are certainly not tailored towards Sileo in any significant degree. The only gripe I can see from the surface level is that “Sileo” is in the control file key. I feel as though this is another unnecessary and complicated division that the community, and most importantly repo maintainers, doesn’t want.

**Comment by coolstar** [comment] 2020-05-28 00:28
The critical flaw with the proposal for these native depictions is:

1. Lack of flexibility for repos to define the layout of the depiction (hence why the Sileo Depiction format was designed the way it is)
2. Potentially large description text in the control file
3. Potentially large changelog text in the control file

2 & 3 are especially egregious as for repos hosting multiple versions of packages, the text sizes in the "Packages" file can get especially big, and result in massive bloated Packages files that will need to be downloaded on every repo refresh, causing potentially serious bandwidth overhead for many major repos

**Comment by aydenp** [comment] 2020-05-28 00:31
I really like the effort here! Native depictions are something that every package manager should aim to support and that every developer should have access to, regardless of their repo.

However, from a technical perspective, the planned API seems a bit shortsighted:

- Preloaded information density: Placing all of this info — description, changelogs, etc. — in the control file, which is compiled into a Packages file, which is downloaded every time the package manager reloads its sources, sounds like a way to drive up bandwidth usage (making it more expensive to host, pushing people over mobile data limits, etc.), and recreate the problems we see with BigBoss.

One of the limitations of using APT on mobile from the beginning has been that the entire package list has to be loaded ahead of time, rather than on-demand. For example, search queries probably make more sense if sent to the server so it can return only the data that matches, rather than doing this locally. Now, this is less of a problem in 2020, but on a slower device with a data cap, it did have an impact. I worry that shoving all of this rich information into the Packages file will bring back the pain of 2 minute source refreshes. We should not add onto this problem by bundling way more information with these huge files we’re forced to host and download. 

- Repurposing existing control file fields: As you note in the API reference, you use the normal description field that DPKG and Cydia have been using forever. Except, you add markdown to this field, meaning that Cydia users would see markdown littered throughout depictions as they try to read them. You seemingly recognize this problem, which is why preferring these depictions is another opt-in field in the control file. I think it’s best to keep the description field plain, simple, and free of markup, to preserve this backwards compatibility.

- Shifting responsibility: The community currently accepts that in the cases where the repo maintainer and package developer are not the same entity, the repo maintainer has control over the depiction of the package. Many repos use this opportunity to provide relevant information to simplify the development process (almost all default repos and repo-creation tools over some convenient editor UI). With this proposal, the onus would now be on the developer to provide all the information displayed, unless repos want to be rewriting DEB files or creating a disparity between the control and Packages files’ contents.

- Fragmentation: As referenced earlier, this proposal means that there is now one more API for repos (or maybe, due to my previous point, developers) to support. To be completely honest, this has already been a terrible experience for repo maintainers. We have to support a growing and complex matrix of configurations, featuring device model, package manager (and its features), jailbreak bootstrap (APT version). This means that we’ve had to do hacky things to accommodate for unexpected disparities, from deliberate ones such that Zebra uses the payment API (intended for use in combination with Sileo’s native depictions), but would display web depictions, meant for Cydia (with payment UI still present), and also from accidental: Zebra not showing native payment UI unless the user was already signed in. I’m listing Zebra issues because you’ll have insight into these, but every package manager has discrepancies like these now, and they are not fun for our support staff to have to workaround.

---

I really, 100% honestly, admire and appreciate the intent and work that has gone into this proposal: I like that it tries to give smaller developers who host their own repos a chance to use native depictions without too much extra effort. I know it wasn’t exactly aimed at larger repos. But I really hope you consider my and others’ feedback before getting too far into it.

I’m happy to discuss any of the points I’ve mentioned here further, and offer myself for you bounce any ideas any ideas off of. I think that with an open exchange of ideas we could turn this into a feature that benefits all involved!

**Comment by absidue** [comment] 2020-05-28 00:36
As someone who has just looked at the Sileo native depiction documentation for the first time, I am missing code examples and images of what it looks like in Sileo. As the documentation is currently I would have to look at the depictions of existing repos and refer back to the documentation to find out what each key does. I wouldn't be able to start from the documentation alone.

I was going to open an issue about it but I got this error when trying to open your JIRA page:
![image](https://user-images.githubusercontent.com/48293849/83085104-39de7500-a08b-11ea-8e19-4ed3264b8669.jpeg)

**Comment by Shugabuga** [comment] 2020-05-28 00:46
@adsidue Sileo no longer uses Jira, but the repo on GitHub, to my knowledge.

Also, I can add screenshots for each element if that's an issue. I already have a reference, https://repotest.shuga.co/, that I use to test implementations.

**Comment by Shugabuga** [comment] 2020-05-28 00:46
Okay, I'm going to be honest here: I don't think making another depiction format is the way to move forward. The UI is stellar and everything I hoped it would be, but its implementation is a _lot_ more annoying than the [native depiction](https://developer.getsileo.app/native-depictions) spec created by Sileo, which has become the new standard.

Before I begin on why I feel this way, I want to mention my angle at this and lay my biases in the clear. I'm the developer of [Silica](https://github.com/Shugabuga/Silica), a repo generation tool. [I am also in charge of documenting native depictions in Sileo](github.com/Sileo/DeveloperDocumentation/) and am about to publish Kennel, a NodeJS native depiction renderer written in TypeScript. So I *am* familiar with how Sileo does things, and I'm not going to pretend I'm going at this neutrality because I am not. All humans have their biases, and ignoring them would be deceptive.

My argument boils down to a few key points:

- Fragmentation is bad for everybody.
- A different spec could be more confusing for new developers.
- Having elements in the `Control` file consumes more space than referencing an external document.
- This is more limiting than Sileo's native depictions, which have gotten critisism for their lack of customizability.

(For the remainder of this response, I will be referring to Sileo's native depictions as just "native depictions," as that is what they are officially called in the documentation. I will be calling Zebra's native depictions "Zebra depictions" to make the distinction easier.)

### Fragmentation and Developer Confusion

![xkcd 927](https://imgs.xkcd.com/comics/standards.png)

[*xkcd 927*](https://xkcd.com/927/)

First, making another standard is just silly. As they say, *why reinvent the wheel?* By introducing your new format, you are now adding more variables for repos both big and small have to deal with, and making a small repo is already confusing as it is for newcomers. I know first-hand how hard getting basic support is (it took me way too long to make my first repo), so adding the variable of "how should I make my repo look nice" should be a simple answer. We should strive, as a community, to make basic tasks like having depictions uniform throughout all package managers, and this does the opposite.

As for lowering barriers to entry, I totally agree with that. I also do know that Sileo depictions can be a bit intimidating at first, and I strive to make tools to make it easy irregardless of experience (Silica was built with this in mind). However, making a new standard is counterntuitive in this goal, and formatting a Control file without breaking it can be a struggle for beginners (I see the extended taglines being a common point of confusion).

As for adoption, native depictions are quite common, even more so than HTML depictions. Sileo, Installer, Saily, and even the web-based (to be released) Parcility use it to some degree, making Zebra the only modern package manager to not express interest in the format. Even Cydia has back-ported support, as seen in PixelOmer's \[\[ModernDepictions\]\].

![Support of each depiction type.](https://pbs.twimg.com/media/EZDiaUvWoAAwVuo?format=jpg&name=medium)

### File Size

On the modern Internet, people don't care about file sizes. Sites are way too big for their own good, games can easily take a few gigabytes, and high-quality images can be a few megabytes. But what about those who don't have the luxury of fast Internet? DSL is still used a lot in the rural United States, and it's unbearable.

But how does this relate to Zebra depictions? Now, irregardless if the user uses Zebra or not, the file sizes of repository-related files will increase dramatically if changelogs and extended descriptions are utilized to their full potential. Sileo's native depictions deal with this by having it be a separate web request, allowing the extra data to be ignored if a package manager doesn't support it. However, Zebra depictions will add changelog and description data on most repo calls, increasing load times and bandwidth costs. This could cause a worsened experience for users with slower Internet connections, regardless of their package manager.

This can be resolved by linking the data elsewhere, which is what is currently done by both HTML and Native depictions, and fetching it on demand.

### Customizability

When Sileo Team launched native depictions, it was met with a lot of critisim. I noticed that you opted to make these depictions opt-in to try to reduce the ad-related concerns, but another raised by people like Nepeta was a percieved lack of customizability. Knowing the spec myself, I disagree with those claims; there are a lot of underutilized settings, including custom CSS, that repos and developers could utilize.

However, Zebra depictions have none of that; it's just some images, some Markdown text, and screenshots. No custom colors, non-screenshot images, custom table field (such as price or a misc. button), or anything of the sort. I get the format is beginner-centric, but who wouldn't want to spruce up their repo's depictions a bit if they could? Branding is key, and native depictions offer a nice in-between between user experience and customization.

#### "Porting" Native Depictions

You mentioned native depictions being "converted" to this format. That's a bad idea, but not because of analytics or ad revenue, but because Sileo depictions are heavily customizable, making it hard to determine what `DepictionMarkdownView` is a description or what one is serving some other role. This can cause depitions to get butchered, lost in interpretation, or a sleugh of other issues. Similarly, you can't always rely on `tabs[1]` to be a changelog, because it could be whatever the repo decides it should be. Installer attempts this in 5.0, but it's  limiting and *feels* off, and to my knowledge, they are working into their own native depiction implementation in 5.1.

### Final Regards

I know you wrote this spec with good intentions, but it's unfortunately inheritly flawed. File sizes rack up quick, new developers can get overwhelmed with the "standards hell" this furthers, and it's relatively static for a developer scene where building a brand is key. For all of these reasons, I don't think creating your own standard is a good idea. Most repo developers and I implore you to adapt the native depiction spec properly, many sharing similar reasons as I.

Thank you for holding this forum for comments,

- Shuga

**Comment by absidue** [comment] 2020-05-28 00:53
> @adsidue Sileo no longer uses Jira, but the repo on GitHub, to my knowledge.
> 
> 
> 
> Also, I can add screenshots for each element if that's an issue. I already have a reference, https://repotest.shuga.co/, that I use to test implementations.

Could you please update the "file an issue on our issue tracker" link in the documentation

**Comment by Shugabuga** [comment] 2020-05-28 00:58
@absidue Sure thing. I'll just link to Sileo 2.0's repo.

**Comment by wstyres** [comment] 2020-05-28 01:54
@23Aaron 

> Adding another depiction standard at this point is already frustrating enough for major repos to support (even if the argument is that this change isn't made with large repos to support, smaller repos will look to us as an example/guidance)

As you said, the intention here is not for this to be a replacement for web depictions on major repositories. If a `Depiction` tag is present at all in a package control file, we won't even try to render a native depiction and the web one will be shown instead. The intention is for smaller developers to be able to stray away from "An Awesome MobileSubstrate Tweak!" in Cydia that we all know and love.

> Devs will likely not be able to focus on ensuring all depictions look good, so some will optimise for Sileo and others for Zebra. Fragmentation at this point along the development of Sileo's native depictions is something we should really be aiming to avoid.

I agree, more fragmentation is something I do not want and I suspect no one wants and that is why this discussion area exists. We've put our ideas out here for community discussion so that everyone has a voice. We're more than willing to steer ship and change the direction of these depictions if the community and we agree on a solution.

> If the aim is simplicity, why would a developer not simply stick with existing webview depictions?

They can, and that is perfectly all right. We're not forcing anyone to conform to these new depictions. In my personal opinion, adding a few extra fields into my control file is way less effort than having to create a webpage, writing CSS, and ensuring that it all looks good.

> I take issue with the assessment that
  "We didn't want to (fully) implement Sileo's Depiction format as we found that it is very catered towards Sileo's use and not very open to other package managers"
  As Zebra seems to be the only package manager which is taking this stance. Installer 5 managed to integrate Sileo's native depictions with no issues, along with Parcility, and to my knowledge, Saily.

I might need to re-phrase myself here. As we see it, the problem with Sileo's depictions is that if we implement them, we either go all in or we don't do it at all. Previously, we were under the impression that we could simply convert Sileo's depiction format into Zebra's but this doesn't seem to be the case as Sileo's is extremely customizable and there is no set in stone structure.

> I also believe that the reasoning that
  "the JSON format can quickly get confusing and very messy"
  is a strange one, because you're eschewing a known entity, and one well documented for an approach that requires additions to control files that seem like a completely new addition to something else entirely?

While Sileo's native depictions are well documented, that doesn't mean they are easy. While Silica can be super handy, there is a reason why tools like it exist. For a new developer trying to support native depictions, working with it isn't exactly straightforward. There is a lot of testing needed as well as a lot of control to the point where it may seem intimidating for someone trying to implement it. To people who understand the format and may have worked on creating it, this may not seem like an issue. 

> All in all, my thoughts on this is that it's a confusing move, I don't see who it seeks to benefit, and only seems to cause fragmentation in an area that was currently doing fine without it. I really enjoy Zebra as a whole, and I'm sure this move has good intentions behind it, but I can't see it benefitting the community as a whole.

For a repo like Dynastic that might have tools and templates to easily generate depictions for every package, not every developer has access to this. I want to emphasize the point that this is not targeted at bigger repositories. We're just trying to allow smaller developers to not worry so much about how their package depiction appears and rather focus on the functionality of the package itself.

**Comment by avibhasin81** [comment] 2020-05-28 02:06
There is a bug in zebra beta 1 its showing 2 updates after upgrading it still showing me that same 2 updates again

**Comment by Shugabuga** [comment] 2020-05-28 02:07
@avibhasin81 I would consider filing a separate issue, as that sounds like a bug. This is for discussion on the new depictions.

**Comment by wstyres** [comment] 2020-05-28 02:10
https://github.com/wstyres/Zebra/issues/1309#issuecomment-635009213

> I’d like to note that the native depictions introduced by Sileo are well documented and open to change, as stated from the beginning. They were made to introduce a new standard, and are certainly not tailored towards Sileo in any significant degree. The only gripe I can see from the surface level is that “Sileo” is in the control file key. I feel as though this is another unnecessary and complicated division that the community, and most importantly repo maintainers, doesn’t want.

- Since the Sileo team is in charge of the depiction API, they can decide at any point to edit, add, or remove certain fields. For Sileo itself, this isn't a problem as they can coordinate API updates to be in sync with the app. For other package managers, such as Installer and Zebra, there will be a delay in when the changes are supported. This can lead to depictions rendering differently among package managers. The changes we are proposing, rather, are very generic and shouldn't need to change at any point. The data is there and package managers can choose to display it however they see fit.
- Repo Maintainers creating a "Sileo Depiction" may assume that this depiction will only be shown in Sileo. It is somewhat confusing when other package managers also use the depiction.

**Comment by Shugabuga** [comment] 2020-05-28 02:14
Even though this is a spec aimed at beginners, it does have the side effect that it only works on Zebra. If a developer opts for this instead of a native or web depiction, then their depictions only work in Zebra, unless there's an effort to make this work on every major package manager (which I'm skeptical will happen).

If we want to make a more beginner-friendly native depiction spec, we need to work with other package managers in tandem and possibly try to use the native depiction spec as it is now to try to reduce compatibility issues.

**Comment by Shugabuga** [comment] 2020-05-28 02:15
> Repo Maintainers creating a "Sileo Depiction" may assume that this depiction will only be shown in Sileo. It is somewhat confusing when other package managers also use the depiction.

Yes, the tag is misleading, but it's what was decided a while ago and we just kinda have to stick with it, unfortunately. In a way, it's like the `cydia::commercial` tag; it's branded after Cydia but is now separate from Cydia Store.

**Comment by Diatrus** [comment] 2020-05-28 02:18
> https://github.com/wstyres/Zebra/issues/1309#issuecomment-635009213
> 
> 
> 
> > I’d like to note that the native depictions introduced by Sileo are well documented and open to change, as stated from the beginning. They were made to introduce a new standard, and are certainly not tailored towards Sileo in any significant degree. The only gripe I can see from the surface level is that “Sileo” is in the control file key. I feel as though this is another unnecessary and complicated division that the community, and most importantly repo maintainers, doesn’t want.
> 
> 
> 
> - Since the Sileo team is in charge of the depiction API, they can decide at any point to edit, add, or remove certain fields. For Sileo itself, this isn't a problem as they can coordinate API updates to be in sync with the app. For other package managers, such as Installer and Zebra, there will be a delay in when the changes are supported. This can lead to depictions rendering differently among package managers. The changes we are proposing, rather, are very generic and shouldn't need to change at any point. The data is there and package managers can choose to display it however they see fit.
> 
> - Repo Maintainers creating a "Sileo Depiction" may assume that this depiction will only be shown in Sileo. It is somewhat confusing when other package managers also use the depiction.

Addressing the first point(s?): The “Sileo Team” controlling the spec is a nonissue. If you or Installer actually cared about working together to create a real native depiction system you would have contacted the “Sileo Team” with any concerns about how the current spec wouldn’t fit into your manager, and we would have likely obliged. There’s no reason why the three package managers can’t cooperate to be on top of API changes to the **already established** standard. 

The last point is somewhat of a nonissue, I believe. You’re honestly making a big assumption that repo maintainers have no clue how maintaining a repo works, in which case they would do a quick Google and find out that SileoDepiction: is supported in almost every modern package manager. The “confusion” is on the same level of the confusion a repo maintainer may face when they see Zebra outputs a user-agent of Telesphoreo when it has nothing to do with Telesphoreo, or the fact that there are many standardized Tags used in control files that include `cydia:` that are supported outside of cydia.

**Comment by wstyres** [comment] 2020-05-28 02:29
https://github.com/wstyres/Zebra/issues/1309#issuecomment-635016749

> Lack of flexibility for repos to define the layout of the depiction (hence why the Sileo Depiction format was designed the way it is)

This is why we still support web depictions. What we propose is what the majority of repositories would need to display. If a need arises to add other fields we have no problem with that. The intent behind Zebra's depictions is that it is super simple and looks great. For maintainers concerned about customization, that is what web depictions are for—which provides even more customization than what the Sileo API could offer. Chariz and Dynastic both have a beautiful web depiction in Zebra, just as an example.

> Potentially large description text in the control file

This is a valid concern, but this isn't targeted with repositories with thousands of packages. Again, this is for small developers who want a quick an easy solution to a depiction. Descriptions and changelogs could be moved into a JSON format so that they are only downloaded when needed.

> Potentially large changelog text in the control file that gets bigger with each package update

I think you misunderstood how the changelogs work and that may be my fault explaining. Each package control file only contains the changes for that version. If a repo supports multiple versions and downgrading, a full version history can be shown.

**Comment by wstyres** [comment] 2020-05-28 03:06
https://github.com/wstyres/Zebra/issues/1309#issuecomment-635017711

> Preloaded information density: Placing all of this info — description, changelogs, etc. — in the control file, which is compiled into a Packages file, which is downloaded every time the package manager reloads its sources, sounds like a way to drive up bandwidth usage (making it more expensive to host, pushing people over mobile data limits, etc.), and recreate the problems we see with BigBoss.

I somewhat addressed this in my response to coolstar here: https://github.com/wstyres/Zebra/issues/1309#issuecomment-635056890. I want to point out that Zebra doesn't actually download your package files again if your server or CDN is configured to support the `If-Modified-Since` header. Packages files should be compressed and Zebra supports `.xz`, `.bz2`, `.gz`, and `.lzma`. I haven't run the actual calculations myself for cost as I don't host a major repository but I do see this as a genuine concern. 

> One of the limitations of using APT on mobile from the beginning has been that the entire package list has to be loaded ahead of time, rather than on-demand. For example, search queries probably make more sense if sent to the server so it can return only the data that matches, rather than doing this locally. Now, this is less of a problem in 2020, but on a slower device with a data cap, it did have an impact. I worry that shoving all of this rich information into the Packages file will bring back the pain of 2 minute source refreshes. We should not add onto this problem by bundling way more information with these huge files we’re forced to host and download.

Totally valid, but as stated before, we don't intend on big repositories adopting this. Web works great and we don't want to change that.

> Repurposing existing control file fields: As you note in the API reference, you use the normal description field that DPKG and Cydia have been using forever. Except, you add markdown to this field, meaning that Cydia users would see markdown littered throughout depictions as they try to read them. You seem to partially recognize this problem, that the current use of the description field is reserved for a ‘dumber’ representation, which is why preferring these depictions is another opt-in field in the control file. I think it’s best to keep the description field plain, simple, and free of markup, to preserve this backwards compatibility.

I'm glad you pointed this out as it did not occur to us. We will backtrack on this and not support markdown in the description field. As we mentioned in another response a JSON file could be a more proper solution to providing markdown support and solving the bandwidth issues.

> Shifting responsibility: The community currently accepts that in the cases where the repo maintainer and package developer are not the same entity, the repo maintainer has control over the depiction of the package. Many repos use this opportunity to provide relevant information to simplify the development process (almost all default repos and repo-creation tools over some convenient editor UI). With this proposal, the onus would now be on the developer to provide all the information displayed, unless repos want to be rewriting DEB files or creating a disparity between the control and Packages files’ contents.

We understand that if a repository is a marketplace that they might want to display more information about purchases or branding. Our idea for this is that bigger repositories like Dynastic would be opting to use web depictions instead as it allows for more customization.

> Fragmentation: As referenced earlier, this proposal means that there is now one more API for repos (or maybe, due to my previous point, developers) to support. To be completely honest, this has already been a terrible experience for repo maintainers. We have to support a growing and complex matrix of configurations, featuring device model, package manager (and its features), jailbreak bootstrap (APT version). This means that we’ve had to do hacky things to accommodate for unexpected disparities, from deliberate ones such that Zebra uses the payment API (intended for use in combination with Sileo’s native depictions), but would display web depictions, meant for Cydia (with payment UI still present), and also from accidental: Zebra not showing native payment UI unless the user was already signed in. I’m listing Zebra issues because you’ll have insight into these, but every package manager has discrepancies like these now, and they are not fun for our support staff to have to workaround.

Web depictions are still supported, this new system would be fully optional and again catered to smaller developers hosting a few packages rather than larger repositories. The "not display price information unless logged in" was a bug in our 1.0 release due to some faulty logic and it was resolved in 1.1.

> Flexibility: I also agree entirely with others about the flexibility for repos and developers to do things that hadn’t originally been envisioned. With both web and Sileo’s depictions, we can control the layout of the page to add important UI controls for our repo, such as the Redeem Gift Code button. With this proposal, it seems like there are few places for anything outside of the strict bounds outlined here.

This functionality is not changed by this new format, while Sileo Depictions definitely allow for more customization, web will always be more customizable as seen by the current Dynastic web depictions (which look amazing by the way).

> I really, 100% honestly, admire and appreciate the intent and work that has gone into this proposal: I like that it tries to give smaller developers who host their own repos a chance to use native depictions without too much extra effort. I know it wasn’t exactly aimed at larger repos. But I really hope you consider my and others’ feedback before getting too far into it.

Thank you! We appreciate the feedback as that is what this discussion forum is for. We wanted to get constructive criticism on this before moving any further with this project.

> I’m happy to discuss any of the points I’ve mentioned here further, and offer myself for you bounce any ideas any ideas off of. I think that with an open exchange of ideas we could turn this into a feature that benefits all involved!

For sure! We'd be open to chat about this once we finalize a better plan.

**Comment by Greigh** [comment] 2020-05-28 04:07
I know you kind of mentioned using the change log tag but it would be nice to at least see the last updated date.

**Comment by cj81499** [comment] 2020-05-28 04:11
I don't think I have anything to contribute to this conversation (aside from the various thumbs ups I've left), but just as an FYI for @wstyres the link to the docs in the initial post in this issue is wrong. It should be https://github.com/wstyres/Zebra/wiki/Native-Depictions

**Comment by aydenp** [comment] 2020-05-28 06:05
[#1309 (comment)](https://github.com/wstyres/Zebra/issues/1309#issuecomment-635017711)

Thanks for responding!

> I somewhat addressed this in my response to coolstar here: [#1309 (comment)](https://github.com/wstyres/Zebra/issues/1309#issuecomment-635056890). I want to point out that Zebra doesn't actually download your package files again if your server or CDN is configured to support the `If-Modified-Since` header. Packages files should be compressed and Zebra supports `.xz`, `.bz2`, `.gz`, and `.lzma`. I haven't run the actual calculations myself for cost as I don't host a major repository but I do see this as a genuine concern.

I wouldn't say cost is a concern for us, but it shouldn't have to be a concern for anyone. Despite `If-Modified-Since` and compression, the fact still exists that we'd be frequently downloading lots of detailed data (at least 99% of which the user will not use during the session).

> I'm glad you pointed this out as it did not occur to us. We will backtrack on this and not support markdown in the description field. As we mentioned in another response a JSON file could be a more proper solution to providing markdown support and solving the bandwidth issues.

All of the above said, I think this is a good change to address the bandwidth issues, if we're going all in on that.

> We understand that if a repository is a marketplace that they might want to display more information about purchases or branding. Our idea for this is that bigger repositories like Dynastic would be opting to use web depictions instead as it allows for more customization.
> This functionality is not changed by this new format, while Sileo Depictions definitely allow for more customization, web will always be more customizable as seen by the current Dynastic web depictions (which look amazing by the way).

I do have concerns about offering a feature like this only intended for use by a subset of repos. At some point, users would come to expect native depictions (especially with all the UI work going into it!) and it seems... weird... to have this much effort dedicated to native depictions that is fundamentally not suitable for larger repos. I think we should try as hard to make a universal solution, rather than having a confusing and unspoken eligibility criteria.

> Web depictions are still supported, this new system would be fully optional and again catered to smaller developers hosting a few packages rather than larger repositories. The "not display price information unless logged in" was a bug in our 1.0 release due to some faulty logic and it was resolved in 1.1.

I understand that! My intent in mentioning it was to illustrate some of the challenges that this fragmentation has caused, which was tons of confused users, and that's only including the ones who actually went out of their way to contact support.

My concerns about fragmentation are still strong. Even in Zebra itself, this change will add more complexity that can result in weird bugs, except they'll be harder to reproduce! And regardless of adoption, it still adds just another thing to which developers must conform. In an ideal world, this proposal would mean depictions are effortless. In the real world, it just means that developers will have to do extra work because they can't stop at only supporting Zebra. This means adding more variables to that matrix I mentioned.

> For sure! We'd be open to chat about this once we finalize a better plan.

Looking forward to it! I really hope we can get somewhere with this.

**Comment by kirb** [comment] 2020-05-28 06:27
> I think you misunderstood how the changelogs work and that may be my fault explaining. Each package control file only contains the changes for that version. If a repo supports multiple versions and downgrading, a full version history can be shown.

A slight nitpick there: I don’t want to keep every version ever on my repo, but I do want a complete changelog back to the first version. Just don’t want this information to disappear from the internet because repo owners want to clean up their ancient packages and not get bug reports for them. 

There was a spec I proposed a long time ago (2015 I think? ouch) for a “modern” repo format that didn’t catch on or really get much feedback. The premise was the same as what’s being proposed here - make it easier to present data in a nice prebuilt template kind of way, remove some of the guesswork (what works in a depiction? how can I test it?), while not changing anything for people who want to do things the traditional way (e.g. Chariz wouldn’t be using this). I’ll try and dig it up because I think it’s a cleaner approach and solves issues @aydenp mentioned, while still being compatible with package managers not supporting this system.

**Comment by p0358** [comment] 2020-05-29 19:24
The biggest issue here, I think, is that these most likely won't be supported by other package managers. So someone making a new repo will still need to add web and/or sileo depictions anyways, unless they want other package managers to just display the "Description" field. Which kinda defeats the purpose, since they could just as well use the same web depiction they'd make for Cydia in Zebra, probably. The JSON solution does solve some of the other issues though.

But about modifying contents of Packages file: isn't that the case with some repos already? Or do developers need to supply the correct Depiction and SileoDepiction URLs before compiling and submitting to a public repo? I have a script on my own repo that does add depictions and icons only to Packages file, and it works great in Zebra so far, is that a wrong way to do it?

I'm definitely looking forward to @Shugabuga's Kennel project, because that's the biggest issue I've had with Sileo depictions. It should solve 2 issues at once:
* would let repo maintainers write depictions once and then render them in webview for compatibility with package managers that only support webviews
* it could be used to quickly test the looks, without having to have Sileo at all, without having to upload the depiction and wait for packages to refresh.
Btw @Shugabuga would it be dynamically rendered from a NodeJS server, or would it create static files, or both? I'm thinking how it could solve dark mode support for instance in Zebra, where it's supplied with headers, but also available in user-agent for client-side JS currently

**Comment by Shugabuga** [comment] 2020-05-29 20:22
[re: @p0358]

> But about modifying contents of Packages file: isn't that the case with some repos already?

Yeah, it's already done by repos, but multi-line Description and Changelog entries take more space than usual.

> [re: Kennel]

It's a NodeJS module, so **implementation is up to the user**. [Parcility](https://twitter.com/Parcility/status/1265779218635526152) uses Kennel to render depictions dynamically by requesting the `SileoDepiction` JSON and passing the output to Kennel. However, you can also do it statically, which is what [the provided demo](https://github.com/ZenithDevs/Kennel/blob/master/demo/index.js) does (link will 404 until Kennel is released). The [Parcility API](https://parcility.co) will also provide endpoints for rendering a formatted native depiction, given a URL or bundle ID, that is fit for depiction usage if you don't want to mess with tweaking styles and whatnot (as Kennel intentionally only styles the elements, leaving the rest to the user).

**Comment by nullpixel** [comment] 2020-05-31 18:42
I echo the sentiments of @aydenp and @kirb in that this spec has some pretty big limitations.

I'm not that creating a spec which only really works for smaller repos is a great idea because our users will too expect the native depiction experience, which would be totally unfeasible for us to implement with this current specification. 

Perhaps a good compromise would be implementing Sileo depictions and then building a simpler form of that for smaller repos, only supporting the keys you propose here?

**Comment by Shugabuga** [comment] 2020-05-31 22:10
I'm all for a way to make a simpler form of Sileo's native depictions. We could propose this as a separate class distinct from the rest. The only thing I would be worried about is implementing changelogs in such a format.

A basic depiction utilizing a hypothetical `DepictionBasicView`:
```json
{
    "minVersion": "0.1",
    "headerImage": "https://example.com/banner.png",
    "class": "DepictionBasicView",
    "tintColor": "#6264D3",
    "screenshots": [
        {
            "accessibilityText": "Screenshot #1",
            "url": "https://repo.shuga.co/assets/heyitsshuga.lunadarkmode/screenshot/01.png"
        },
        {
            "accessibilityText": "Screenshot #2",
            "url": "https://repo.shuga.co/assets/heyitsshuga.lunadarkmode/screenshot/03.png"
        }
    ],
    "markdown": "Just some Markdown-compatible text. Woo!"
}
```
I tried to design this dummy depiction with how depictions are already rendered in mind. There's also no tab view here, and if implemented, I'd say that no tabs should be displayed (which may be an issue if current implementations assume that tabs will always be present).

A flaw, however, is the aforementioned changelogs. There's two schools of thought on how changelogs should be handled: as a separate tab (Sileo) or as a section on the same page (Zebra). This worries me because how Sileo native depictions work is that they're just rendering whatever it gets without saying "this is a changelog." So, either we can add on an additional `changelog` property (or similar) that creates such a box, or mandate it through tabs ([which probably could work](https://gist.github.com/Shugabuga/388497a2fe3fa65a779b521b6d989f63), albeit that goes against the idea of this being a beginner-friendly solution). Debian changelogs may also be an option.

Comments are appreciated, especially about the changelog problem.

**Closed** 2020-12-09 03:36 UTC
Labels: packages, suggestion

**Comment by 10Meisterbaelle** [comment] 2022-05-01 11:46
I think web depictions work fine, native depictions are just restrictive.
