### ISSUE TITLE
Crash when attempting to go into “Changes” tab

### ISSUE THREAD

**Issue by whiteblacksmiths** [zbrateam/Zebra#1760] opened 2021-03-06 11:21 UTC
**Describe the bug**

since 1.2\~beta7a, when i refresh my sources, all the sources would load, and from the “installed” tab i can see that they are in fact loaded, but when i go into the “changes” tab, zebra immediately crashes. the last working version is 1.2\~beta6a for me, but now when i try to downgrade it, the “changes” tab remains empty even after reloading my sources multiple times. it may be because i have 110 repos loaded, but am not certain what exactly is the issue. 

**To Reproduce**

upgrade zebra to version1.2~beta7a and above, and refresh sources. after which, tap on “changes” tab and zebra will crash. 

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <14.3>
 - Zebra Version: <1.2\~beta9a>
 - Device Type: <iPhone X>
 - Jailbreak Type: <unc0ver>

**Crash Log or System Log**

cr4shed has not been working for me since updating to 14.3, so i only have the log from crashreporter: https://pastebin.com/539W6KiD

**Additional context**

**Comment by PoomSmart** [comment] 2021-03-06 12:48
Duplicate of #1735

**Closed by PoomSmart** 2021-03-06 12:48 UTC
Labels: bug
